# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forming.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Forming(object):
    def setupUi(self, Forming):
        Forming.setObjectName("Forming")
        Forming.resize(1050, 730)
        Forming.setMinimumSize(QtCore.QSize(1050, 550))
        self.gridLayout_2 = QtWidgets.QGridLayout(Forming)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(Forming)
        self.widget.setMinimumSize(QtCore.QSize(350, 350))
        self.widget.setMaximumSize(QtCore.QSize(350, 431))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_label = QtWidgets.QLabel(self.widget)
        self.title_label.setMinimumSize(QtCore.QSize(0, 24))
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_label.setObjectName("title_label")
        self.verticalLayout_2.addWidget(self.title_label)
        self.setting_label = QtWidgets.QLabel(self.widget)
        self.setting_label.setMinimumSize(QtCore.QSize(0, 24))
        self.setting_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.setting_label.setObjectName("setting_label")
        self.verticalLayout_2.addWidget(self.setting_label)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.source = QtWidgets.QComboBox(self.frame)
        self.source.setEnabled(False)
        self.source.setObjectName("source")
        self.source.addItem("")
        self.source.addItem("")
        self.gridLayout.addWidget(self.source, 2, 2, 1, 1)
        self.source_label = QtWidgets.QLabel(self.frame)
        self.source_label.setObjectName("source_label")
        self.gridLayout.addWidget(self.source_label, 2, 1, 1, 1)
        self.temp_check = QtWidgets.QCheckBox(self.frame)
        self.temp_check.setObjectName("temp_check")
        self.gridLayout.addWidget(self.temp_check, 9, 1, 1, 1)
        self.fname_label = QtWidgets.QLabel(self.frame)
        self.fname_label.setObjectName("fname_label")
        self.gridLayout.addWidget(self.fname_label, 1, 1, 1, 1)
        self.vEnd_label = QtWidgets.QLabel(self.frame)
        self.vEnd_label.setObjectName("vEnd_label")
        self.gridLayout.addWidget(self.vEnd_label, 4, 1, 1, 1)
        self.vStart_label = QtWidgets.QLabel(self.frame)
        self.vStart_label.setObjectName("vStart_label")
        self.gridLayout.addWidget(self.vStart_label, 3, 1, 1, 1)
        self.temperature = QtWidgets.QDoubleSpinBox(self.frame)
        self.temperature.setEnabled(False)
        self.temperature.setMaximum(600.0)
        self.temperature.setProperty("value", 300.0)
        self.temperature.setObjectName("temperature")
        self.gridLayout.addWidget(self.temperature, 9, 2, 1, 1)
        self.file_name = QtWidgets.QLineEdit(self.frame)
        self.file_name.setObjectName("file_name")
        self.gridLayout.addWidget(self.file_name, 1, 2, 1, 1)
        self.vEnd = QtWidgets.QDoubleSpinBox(self.frame)
        self.vEnd.setDecimals(3)
        self.vEnd.setMinimum(-50.0)
        self.vEnd.setMaximum(49.0)
        self.vEnd.setSingleStep(0.1)
        self.vEnd.setProperty("value", 3.0)
        self.vEnd.setObjectName("vEnd")
        self.gridLayout.addWidget(self.vEnd, 4, 2, 1, 1)
        self.iLimit_label = QtWidgets.QLabel(self.frame)
        self.iLimit_label.setObjectName("iLimit_label")
        self.gridLayout.addWidget(self.iLimit_label, 5, 1, 1, 1)
        self.iLimit = QtWidgets.QDoubleSpinBox(self.frame)
        self.iLimit.setDecimals(3)
        self.iLimit.setMaximum(500.0)
        self.iLimit.setSingleStep(0.001)
        self.iLimit.setProperty("value", 1.0)
        self.iLimit.setObjectName("iLimit")
        self.gridLayout.addWidget(self.iLimit, 5, 2, 1, 1)
        self.vStart = QtWidgets.QDoubleSpinBox(self.frame)
        self.vStart.setDecimals(3)
        self.vStart.setMinimum(-50.0)
        self.vStart.setMaximum(49.0)
        self.vStart.setSingleStep(0.1)
        self.vStart.setProperty("value", 0.0)
        self.vStart.setObjectName("vStart")
        self.gridLayout.addWidget(self.vStart, 3, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(Forming)
        self.widget1.setMinimumSize(QtCore.QSize(350, 151))
        self.widget1.setMaximumSize(QtCore.QSize(350, 10000))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comment_checkBox = QtWidgets.QCheckBox(self.widget1)
        self.comment_checkBox.setObjectName("comment_checkBox")
        self.verticalLayout.addWidget(self.comment_checkBox)
        self.commentBox = QtWidgets.QTextEdit(self.widget1)
        self.commentBox.setEnabled(False)
        self.commentBox.setObjectName("commentBox")
        self.verticalLayout.addWidget(self.commentBox)
        self.start_Button = QtWidgets.QPushButton(self.widget1)
        self.start_Button.setObjectName("start_Button")
        self.verticalLayout.addWidget(self.start_Button)
        self.abort_Button = QtWidgets.QPushButton(self.widget1)
        self.abort_Button.setObjectName("abort_Button")
        self.verticalLayout.addWidget(self.abort_Button)
        self.statusbar = QtWidgets.QLineEdit(self.widget1)
        self.statusbar.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.statusbar.setPalette(palette)
        self.statusbar.setText("")
        self.statusbar.setAlignment(QtCore.Qt.AlignCenter)
        self.statusbar.setReadOnly(True)
        self.statusbar.setObjectName("statusbar")
        self.verticalLayout.addWidget(self.statusbar)
        self.gridLayout_2.addWidget(self.widget1, 1, 0, 1, 1)
        self.graphWidget = PlotWidget(Forming)
        self.graphWidget.setMinimumSize(QtCore.QSize(411, 379))
        self.graphWidget.setObjectName("graphWidget")
        self.gridLayout_2.addWidget(self.graphWidget, 0, 1, 2, 1)

        self.retranslateUi(Forming)
        QtCore.QMetaObject.connectSlotsByName(Forming)
        Forming.setTabOrder(self.file_name, self.source)
        Forming.setTabOrder(self.source, self.vStart)
        Forming.setTabOrder(self.vStart, self.vEnd)
        Forming.setTabOrder(self.vEnd, self.iLimit)
        Forming.setTabOrder(self.iLimit, self.temp_check)
        Forming.setTabOrder(self.temp_check, self.temperature)
        Forming.setTabOrder(self.temperature, self.comment_checkBox)
        Forming.setTabOrder(self.comment_checkBox, self.commentBox)
        Forming.setTabOrder(self.commentBox, self.start_Button)
        Forming.setTabOrder(self.start_Button, self.abort_Button)
        Forming.setTabOrder(self.abort_Button, self.statusbar)

    def retranslateUi(self, Forming):
        _translate = QtCore.QCoreApplication.translate
        Forming.setWindowTitle(_translate("Forming", "Forming"))
        self.title_label.setText(_translate("Forming", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; color:#0000ff;\">Forming</span></p></body></html>"))
        self.setting_label.setText(_translate("Forming", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#aa0000;\">Settings</span></p></body></html>"))
        self.source.setItemText(0, _translate("Forming", "Keysight B2920B"))
        self.source.setItemText(1, _translate("Forming", "Keithley 2450"))
        self.source_label.setText(_translate("Forming", "<html><head/><body><p><span style=\" font-size:10pt;\">Voltage Source</span></p></body></html>"))
        self.temp_check.setToolTip(_translate("Forming", "<html><head/><body><p>Use temperature only if temperature controller is attached</p></body></html>"))
        self.temp_check.setText(_translate("Forming", "Temperature (K)"))
        self.fname_label.setText(_translate("Forming", "<html><head/><body><p><span style=\" font-size:10pt;\">File Name</span></p></body></html>"))
        self.vEnd_label.setText(_translate("Forming", "<html><head/><body><p><span style=\" font-size:10pt;\">Voltage End (V)</span></p></body></html>"))
        self.vStart_label.setText(_translate("Forming", "<html><head/><body><p><span style=\" font-size:10pt;\">Voltage Start (V)</span></p></body></html>"))
        self.temperature.setToolTip(_translate("Forming", "<html><head/><body><p>Temperature range will depend on the type of heater</p></body></html>"))
        self.file_name.setText(_translate("Forming", "Sample_Forming"))
        self.vEnd.setToolTip(_translate("Forming", "<html><head/><body><p>Max -10 V</p></body></html>"))
        self.iLimit_label.setText(_translate("Forming", "<html><head/><body><p><span style=\" font-size:10pt;\">Current Limit (mA)</span></p></body></html>"))
        self.iLimit.setToolTip(_translate("Forming", "<html><head/><body><p>The compliance current, which protects the sample from full breakdown</p></body></html>"))
        self.vStart.setToolTip(_translate("Forming", "<html><head/><body><p>Max -10 V</p></body></html>"))
        self.comment_checkBox.setText(_translate("Forming", "Add Comments"))
        self.start_Button.setToolTip(_translate("Forming", "<html><head/><body><p>Click to start the experiment</p></body></html>"))
        self.start_Button.setText(_translate("Forming", "Start"))
        self.abort_Button.setToolTip(_translate("Forming", "<html><head/><body><p>Click to abort the experiment</p></body></html>"))
        self.abort_Button.setText(_translate("Forming", "Abort"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Forming = QtWidgets.QWidget()
    ui = Ui_Forming()
    ui.setupUi(Forming)
    Forming.show()
    sys.exit(app.exec_())

