# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IVloop.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IVLoop(object):
    def setupUi(self, IVLoop):
        IVLoop.setObjectName("IVLoop")
        IVLoop.resize(818, 567)
        IVLoop.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout_2 = QtWidgets.QGridLayout(IVLoop)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(IVLoop)
        self.groupBox.setMinimumSize(QtCore.QSize(240, 260))
        self.groupBox.setMaximumSize(QtCore.QSize(242, 600))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.temperature = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.temperature.setEnabled(False)
        self.temperature.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.temperature.setMaximum(600.0)
        self.temperature.setProperty("value", 300.0)
        self.temperature.setObjectName("temperature")
        self.gridLayout.addWidget(self.temperature, 12, 2, 1, 1)
        self.ncycles_label = QtWidgets.QLabel(self.groupBox)
        self.ncycles_label.setObjectName("ncycles_label")
        self.gridLayout.addWidget(self.ncycles_label, 9, 0, 1, 2)
        self.Ilimit_label = QtWidgets.QLabel(self.groupBox)
        self.Ilimit_label.setObjectName("Ilimit_label")
        self.gridLayout.addWidget(self.Ilimit_label, 7, 0, 1, 2)
        self.scan_speed_label = QtWidgets.QLabel(self.groupBox)
        self.scan_speed_label.setObjectName("scan_speed_label")
        self.gridLayout.addWidget(self.scan_speed_label, 6, 0, 1, 2)
        self.temp_check = QtWidgets.QCheckBox(self.groupBox)
        self.temp_check.setObjectName("temp_check")
        self.gridLayout.addWidget(self.temp_check, 12, 0, 1, 2)
        self.setting_label = QtWidgets.QLabel(self.groupBox)
        self.setting_label.setMinimumSize(QtCore.QSize(0, 24))
        self.setting_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.setting_label.setObjectName("setting_label")
        self.gridLayout.addWidget(self.setting_label, 0, 0, 1, 3)
        self.Ilimit = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Ilimit.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.Ilimit.setDecimals(3)
        self.Ilimit.setMaximum(1.0)
        self.Ilimit.setSingleStep(0.001)
        self.Ilimit.setProperty("value", 0.5)
        self.Ilimit.setObjectName("Ilimit")
        self.gridLayout.addWidget(self.Ilimit, 7, 2, 1, 1)
        self.file_name = QtWidgets.QLineEdit(self.groupBox)
        self.file_name.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.file_name.setObjectName("file_name")
        self.gridLayout.addWidget(self.file_name, 1, 2, 1, 1)
        self.fname_label = QtWidgets.QLabel(self.groupBox)
        self.fname_label.setObjectName("fname_label")
        self.gridLayout.addWidget(self.fname_label, 1, 0, 1, 2)
        self.ncycles = QtWidgets.QSpinBox(self.groupBox)
        self.ncycles.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.ncycles.setMinimum(1)
        self.ncycles.setMaximum(500)
        self.ncycles.setProperty("value", 1)
        self.ncycles.setObjectName("ncycles")
        self.gridLayout.addWidget(self.ncycles, 9, 2, 1, 1)
        self.delay = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.delay.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.delay.setMaximum(10000.0)
        self.delay.setSingleStep(0.05)
        self.delay.setProperty("value", 1.0)
        self.delay.setObjectName("delay")
        self.gridLayout.addWidget(self.delay, 5, 2, 1, 1)
        self.delay_label = QtWidgets.QLabel(self.groupBox)
        self.delay_label.setObjectName("delay_label")
        self.gridLayout.addWidget(self.delay_label, 5, 0, 1, 1)
        self.scan_speed = QtWidgets.QComboBox(self.groupBox)
        self.scan_speed.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.scan_speed.setObjectName("scan_speed")
        self.scan_speed.addItem("")
        self.scan_speed.addItem("")
        self.scan_speed.addItem("")
        self.scan_speed.addItem("")
        self.scan_speed.addItem("")
        self.gridLayout.addWidget(self.scan_speed, 6, 2, 1, 1)
        self.maxV_label = QtWidgets.QLabel(self.groupBox)
        self.maxV_label.setObjectName("maxV_label")
        self.gridLayout.addWidget(self.maxV_label, 4, 0, 1, 2)
        self.maxV = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.maxV.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.maxV.setDecimals(3)
        self.maxV.setMinimum(-9.0)
        self.maxV.setMaximum(10.0)
        self.maxV.setSingleStep(0.001)
        self.maxV.setProperty("value", 3.0)
        self.maxV.setObjectName("maxV")
        self.gridLayout.addWidget(self.maxV, 4, 2, 1, 1)
        self.minV_label = QtWidgets.QLabel(self.groupBox)
        self.minV_label.setObjectName("minV_label")
        self.gridLayout.addWidget(self.minV_label, 3, 0, 1, 2)
        self.minV = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.minV.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.minV.setDecimals(3)
        self.minV.setMinimum(-10.0)
        self.minV.setMaximum(9.0)
        self.minV.setSingleStep(0.001)
        self.minV.setProperty("value", -3.0)
        self.minV.setObjectName("minV")
        self.gridLayout.addWidget(self.minV, 3, 2, 1, 1)
        self.ncycles_label_2 = QtWidgets.QLabel(self.groupBox)
        self.ncycles_label_2.setObjectName("ncycles_label_2")
        self.gridLayout.addWidget(self.ncycles_label_2, 8, 0, 1, 1)
        self.ncycles_2 = QtWidgets.QSpinBox(self.groupBox)
        self.ncycles_2.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.ncycles_2.setMinimum(2)
        self.ncycles_2.setMaximum(1000)
        self.ncycles_2.setProperty("value", 50)
        self.ncycles_2.setObjectName("ncycles_2")
        self.gridLayout.addWidget(self.ncycles_2, 8, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(IVLoop)
        self.widget.setMinimumSize(QtCore.QSize(240, 200))
        self.widget.setMaximumSize(QtCore.QSize(242, 10000))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comment_checkBox = QtWidgets.QCheckBox(self.widget)
        self.comment_checkBox.setObjectName("comment_checkBox")
        self.verticalLayout.addWidget(self.comment_checkBox)
        self.commentBox = QtWidgets.QTextEdit(self.widget)
        self.commentBox.setEnabled(False)
        self.commentBox.setMaximumSize(QtCore.QSize(242, 16777215))
        self.commentBox.setObjectName("commentBox")
        self.verticalLayout.addWidget(self.commentBox)
        self.start_Button = QtWidgets.QPushButton(self.widget)
        self.start_Button.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.start_Button.setObjectName("start_Button")
        self.verticalLayout.addWidget(self.start_Button)
        self.stop_Button = QtWidgets.QPushButton(self.widget)
        self.stop_Button.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.stop_Button.setObjectName("stop_Button")
        self.verticalLayout.addWidget(self.stop_Button)
        self.statusbar = QtWidgets.QLineEdit(self.widget)
        self.statusbar.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.statusbar.setPalette(palette)
        self.statusbar.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.statusbar.setText("")
        self.statusbar.setReadOnly(True)
        self.statusbar.setObjectName("statusbar")
        self.verticalLayout.addWidget(self.statusbar)
        self.gridLayout_2.addWidget(self.widget, 2, 0, 1, 1)
        self.graphwidget = PlotWidget(IVLoop)
        self.graphwidget.setMinimumSize(QtCore.QSize(411, 379))
        self.graphwidget.setObjectName("graphwidget")
        self.gridLayout_2.addWidget(self.graphwidget, 0, 1, 3, 1)

        self.retranslateUi(IVLoop)
        self.scan_speed.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(IVLoop)
        IVLoop.setTabOrder(self.file_name, self.minV)
        IVLoop.setTabOrder(self.minV, self.maxV)
        IVLoop.setTabOrder(self.maxV, self.delay)
        IVLoop.setTabOrder(self.delay, self.scan_speed)
        IVLoop.setTabOrder(self.scan_speed, self.Ilimit)
        IVLoop.setTabOrder(self.Ilimit, self.ncycles_2)
        IVLoop.setTabOrder(self.ncycles_2, self.ncycles)
        IVLoop.setTabOrder(self.ncycles, self.temp_check)
        IVLoop.setTabOrder(self.temp_check, self.temperature)
        IVLoop.setTabOrder(self.temperature, self.comment_checkBox)
        IVLoop.setTabOrder(self.comment_checkBox, self.commentBox)
        IVLoop.setTabOrder(self.commentBox, self.start_Button)
        IVLoop.setTabOrder(self.start_Button, self.stop_Button)
        IVLoop.setTabOrder(self.stop_Button, self.statusbar)

    def retranslateUi(self, IVLoop):
        _translate = QtCore.QCoreApplication.translate
        IVLoop.setWindowTitle(_translate("IVLoop", "IV Loop"))
        self.temperature.setToolTip(_translate("IVLoop", "<html><head/><body><p>Temperature range will depend on the type of heater</p></body></html>"))
        self.ncycles_label.setText(_translate("IVLoop", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of Cycles</span></p></body></html>"))
        self.Ilimit_label.setText(_translate("IVLoop", "<html><head/><body><p><span style=\" font-size:10pt;\">Current Limit (mA)</span></p></body></html>"))
        self.scan_speed_label.setText(_translate("IVLoop", "<html><head/><body><p><span style=\" font-size:10pt;\">Scan Speed</span></p></body></html>"))
        self.temp_check.setToolTip(_translate("IVLoop", "<html><head/><body><p>Use temperature only if temperature controller is attached</p></body></html>"))
        self.temp_check.setText(_translate("IVLoop", "Temperature (K)"))
        self.setting_label.setText(_translate("IVLoop", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Parameters</span></p></body></html>"))
        self.Ilimit.setToolTip(_translate("IVLoop", "<html><head/><body><p>The compliance current, which protects the sample from full breakdown</p></body></html>"))
        self.file_name.setText(_translate("IVLoop", "Sample_IV"))
        self.fname_label.setText(_translate("IVLoop", "<html><head/><body><p><span style=\" font-size:10pt;\">File Name</span></p></body></html>"))
        self.ncycles.setToolTip(_translate("IVLoop", "<html><head/><body><p>Number of cycles to be executed</p></body></html>"))
        self.delay_label.setText(_translate("IVLoop", "<html><head/><body><p><span style=\" font-size:10pt;\">Delay per point (ms)</span></p></body></html>"))
        self.scan_speed.setItemText(0, _translate("IVLoop", "Very Slow"))
        self.scan_speed.setItemText(1, _translate("IVLoop", "Slow"))
        self.scan_speed.setItemText(2, _translate("IVLoop", "Normal"))
        self.scan_speed.setItemText(3, _translate("IVLoop", "Fast"))
        self.scan_speed.setItemText(4, _translate("IVLoop", "Very Fast"))
        self.maxV_label.setText(_translate("IVLoop", "<html><head/><body><p><span style=\" font-size:10pt;\">Maximum Voltage (V)</span></p></body></html>"))
        self.maxV.setToolTip(_translate("IVLoop", "<html><head/><body><p>Max 10 V</p></body></html>"))
        self.minV_label.setText(_translate("IVLoop", "<html><head/><body><p><span style=\" font-size:10pt;\">Minimum Voltage (V)</span></p></body></html>"))
        self.minV.setToolTip(_translate("IVLoop", "<html><head/><body><p>Max -10 V</p></body></html>"))
        self.ncycles_label_2.setText(_translate("IVLoop", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of Points</span></p></body></html>"))
        self.ncycles_2.setToolTip(_translate("IVLoop", "<html><head/><body><p>Number of cycles to be executed</p></body></html>"))
        self.comment_checkBox.setText(_translate("IVLoop", "Add Comments"))
        self.start_Button.setToolTip(_translate("IVLoop", "<html><head/><body><p>Click to start the experiment</p></body></html>"))
        self.start_Button.setText(_translate("IVLoop", "START"))
        self.stop_Button.setToolTip(_translate("IVLoop", "<html><head/><body><p>Click to abort the experiment</p></body></html>"))
        self.stop_Button.setText(_translate("IVLoop", "STOP"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IVLoop = QtWidgets.QWidget()
    ui = Ui_IVLoop()
    ui.setupUi(IVLoop)
    IVLoop.show()
    sys.exit(app.exec_())

