"""
The main GUI for the ReRam Project.

    Just contains the GUI for the main ReRam menu-driven interface

"""

from PyQt5 import QtCore, QtWidgets


class Ui_Memory:
    """The pyqt5 gui class for ReRam project."""

    def setupUi(self, Memory):
        """
        Draw and initialize the main menu.

            Code generated by QT Designer.

        Parameters
        ----------
        Memory : QMainWindow
            Draws the Main menu.

        Returns
        -------
        None.

        """
        Memory.setObjectName("Memory")
        Memory.resize(320, 550)
        Memory.setMinimumSize(QtCore.QSize(320, 550))
        Memory.setMaximumSize(QtCore.QSize(320, 550))
        self.centralwidget = QtWidgets.QWidget(Memory)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dir_Button = QtWidgets.QPushButton(self.centralwidget)
        self.dir_Button.setMinimumSize(QtCore.QSize(0, 40))
        self.dir_Button.setObjectName("dir_Button")
        self.verticalLayout.addWidget(self.dir_Button)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filename_label = QtWidgets.QLabel(self.frame)
        self.filename_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.filename_label.setObjectName("filename_label")
        self.horizontalLayout.addWidget(self.filename_label)
        self.filename = QtWidgets.QLineEdit(self.frame)
        self.filename.setAlignment(QtCore.Qt.AlignCenter)
        self.filename.setObjectName("filename")
        self.horizontalLayout.addWidget(self.filename)
        self.verticalLayout.addWidget(self.frame)
        self.experiment_label = QtWidgets.QLabel(self.centralwidget)
        self.experiment_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.experiment_label.setObjectName("experiment_label")
        self.verticalLayout.addWidget(self.experiment_label)
        self.iv_button = QtWidgets.QPushButton(self.centralwidget)
        self.iv_button.setObjectName("iv_button")
        self.verticalLayout.addWidget(self.iv_button)
        self.rv_button = QtWidgets.QPushButton(self.centralwidget)
        self.rv_button.setObjectName("rv_button")
        self.verticalLayout.addWidget(self.rv_button)
        self.switch_button = QtWidgets.QPushButton(self.centralwidget)
        self.switch_button.setObjectName("switch_button")
        self.verticalLayout.addWidget(self.switch_button)
        self.endurance_button = QtWidgets.QPushButton(self.centralwidget)
        self.endurance_button.setObjectName("endurance_button")
        self.verticalLayout.addWidget(self.endurance_button)
        self.retention_button = QtWidgets.QPushButton(self.centralwidget)
        self.retention_button.setObjectName("retention_button")
        self.verticalLayout.addWidget(self.retention_button)
        self.speed_button = QtWidgets.QPushButton(self.centralwidget)
        self.speed_button.setObjectName("speed_button")
        self.verticalLayout.addWidget(self.speed_button)
        self.aging_button = QtWidgets.QPushButton(self.centralwidget)
        self.aging_button.setObjectName("aging_button")
        self.verticalLayout.addWidget(self.aging_button)
        self.memristor_button = QtWidgets.QPushButton(self.centralwidget)
        self.memristor_button.setObjectName("memristor_button")
        self.verticalLayout.addWidget(self.memristor_button)
        self.temperature_button = QtWidgets.QPushButton(self.centralwidget)
        self.temperature_button.setObjectName("temperature_button")
        self.verticalLayout.addWidget(self.temperature_button)
        self.batch_button = QtWidgets.QPushButton(self.centralwidget)
        self.batch_button.setObjectName("batch_button")
        self.verticalLayout.addWidget(self.batch_button)
        Memory.setCentralWidget(self.centralwidget)
        self.retranslateUi(Memory)
        QtCore.QMetaObject.connectSlotsByName(Memory)

    def retranslateUi(self, Memory):
        """
        Code generated by QT Designer.

        Parameters
        ----------
        Memory : QMainWindow

        Returns
        -------
        None.

        """
        _translate = QtCore.QCoreApplication.translate
        Memory.setWindowTitle(_translate("Memory", "ReRam"))
        self.dir_Button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Choose the directory to save your data. By default, last used directory is chosen.</p></body></html>"))
        self.dir_Button.setText(_translate("Memory", "SELECT DIRECTORY"))
        self.filename_label.setText(_translate(
            "Memory", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#5500ff;\">Sample ID</span></p></body></html>"))
        self.filename.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Enter sample ID. All the experiments will have this ID as prefix in the filename.</p></body></html>"))
        self.filename.setText(_translate("Memory", "Sample"))
        self.experiment_label.setText(_translate(
            "Memory", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#aa0000;\">Choose Experiment</span></p></body></html>"))
        self.iv_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Perform Current Vs Voltage measurement</p></body></html>"))
        self.iv_button.setText(_translate("Memory", "1. IV-Loop"))
        self.rv_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Perform write voltage vs Resistance at read voltage for cyclic write voltages.</p></body></html>"))
        self.rv_button.setText(_translate(
            "Memory", "2. Resistive Switching Loop"))
        self.switch_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Apply set and reset voltage pulses and check its resistance</p></body></html>"))
        self.switch_button.setText(_translate("Memory", "3. Switching Test"))
        self.endurance_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Perform set and reset operations several times and check the stability of the resistive states.</p><p>(Fatigue testing)</p></body></html>"))
        self.endurance_button.setText(
            _translate("Memory", "4. Endurance Test"))
        self.retention_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Check the stability of the set and reset states to read voltage for long time durations.</p></body></html>"))
        self.retention_button.setText(
            _translate("Memory", "5. Retention Test"))
        self.speed_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Test the minimum pulse-width essential for particular write voltage to cause switching</p></body></html>"))
        self.speed_button.setText(_translate("Memory", "6. Switching Speed"))
        self.aging_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Compare the stability of set and reset states after several days.</p></body></html>"))
        self.aging_button.setText(_translate("Memory", "7. Aging Test"))
        self.memristor_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Check the suitability of the device as analogue memory, which is needed for neuromorphic computation</p></body></html>"))
        self.memristor_button.setText(
            _translate("Memory", "8. Memristor Test"))
        self.temperature_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>Check the variation of set and reset resistances with changing temperature.</p></body></html>"))
        self.temperature_button.setText(_translate(
            "Memory", "9. Temperature Dependence"))
        self.batch_button.setToolTip(_translate(
            "Memory", "<html><head/><body><p>An automation program intended to carry out several of the above tests automatically in a pre-determined order.</p></body></html>"))
        self.batch_button.setText(_translate("Memory", "10. Batch Program"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Memory = QtWidgets.QMainWindow()
    ui = Ui_Memory()
    ui.setupUi(Memory)
    Memory.show()
    sys.exit(app.exec_())
