# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Retention.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Retention(object):
    def setupUi(self, Retention):
        Retention.setObjectName("Retention")
        Retention.resize(1050, 603)
        Retention.setMinimumSize(QtCore.QSize(1050, 603))
        self.gridLayout_2 = QtWidgets.QGridLayout(Retention)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Retention)
        self.groupBox.setMinimumSize(QtCore.QSize(222, 370))
        self.groupBox.setMaximumSize(QtCore.QSize(293, 400))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Program_label = QtWidgets.QLabel(self.groupBox)
        self.Program_label.setMinimumSize(QtCore.QSize(0, 24))
        self.Program_label.setMaximumSize(QtCore.QSize(16777215, 24))
        self.Program_label.setObjectName("Program_label")
        self.verticalLayout_2.addWidget(self.Program_label)
        self.setting_label = QtWidgets.QLabel(self.groupBox)
        self.setting_label.setMinimumSize(QtCore.QSize(0, 24))
        self.setting_label.setMaximumSize(QtCore.QSize(16777215, 24))
        self.setting_label.setObjectName("setting_label")
        self.verticalLayout_2.addWidget(self.setting_label)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setPwidth = QtWidgets.QDoubleSpinBox(self.frame)
        self.setPwidth.setDecimals(1)
        self.setPwidth.setProperty("value", 1.0)
        self.setPwidth.setObjectName("setPwidth")
        self.horizontalLayout.addWidget(self.setPwidth)
        self.setTimeUnit = QtWidgets.QComboBox(self.frame)
        self.setTimeUnit.setMaximumSize(QtCore.QSize(41, 22))
        self.setTimeUnit.setObjectName("setTimeUnit")
        self.setTimeUnit.addItem("")
        self.setTimeUnit.addItem("")
        self.setTimeUnit.addItem("")
        self.horizontalLayout.addWidget(self.setTimeUnit)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.avg = QtWidgets.QSpinBox(self.frame)
        self.avg.setWrapping(True)
        self.avg.setAlignment(QtCore.Qt.AlignCenter)
        self.avg.setMinimum(1)
        self.avg.setMaximum(100)
        self.avg.setProperty("value", 5)
        self.avg.setObjectName("avg")
        self.horizontalLayout_3.addWidget(self.avg)
        self.points_label = QtWidgets.QLabel(self.frame)
        self.points_label.setObjectName("points_label")
        self.horizontalLayout_3.addWidget(self.points_label)
        self.gridLayout.addLayout(self.horizontalLayout_3, 13, 1, 1, 1)
        self.readVoltage_label = QtWidgets.QLabel(self.frame)
        self.readVoltage_label.setObjectName("readVoltage_label")
        self.gridLayout.addWidget(self.readVoltage_label, 12, 0, 1, 1)
        self.read_voltage = QtWidgets.QDoubleSpinBox(self.frame)
        self.read_voltage.setProperty("value", 0.1)
        self.read_voltage.setObjectName("read_voltage")
        self.gridLayout.addWidget(self.read_voltage, 12, 1, 1, 1)
        self.temperature = QtWidgets.QDoubleSpinBox(self.frame)
        self.temperature.setEnabled(False)
        self.temperature.setMaximum(600.0)
        self.temperature.setProperty("value", 300.0)
        self.temperature.setObjectName("temperature")
        self.gridLayout.addWidget(self.temperature, 14, 1, 1, 1)
        self.Ilimit_label = QtWidgets.QLabel(self.frame)
        self.Ilimit_label.setObjectName("Ilimit_label")
        self.gridLayout.addWidget(self.Ilimit_label, 10, 0, 1, 1)
        self.temp_check = QtWidgets.QCheckBox(self.frame)
        self.temp_check.setObjectName("temp_check")
        self.gridLayout.addWidget(self.temp_check, 14, 0, 1, 1)
        self.resetV_label = QtWidgets.QLabel(self.frame)
        self.resetV_label.setObjectName("resetV_label")
        self.gridLayout.addWidget(self.resetV_label, 4, 0, 1, 1)
        self.setV_label = QtWidgets.QLabel(self.frame)
        self.setV_label.setObjectName("setV_label")
        self.gridLayout.addWidget(self.setV_label, 2, 0, 1, 1)
        self.vsource = QtWidgets.QComboBox(self.frame)
        self.vsource.setObjectName("vsource")
        self.vsource.addItem("")
        self.vsource.addItem("")
        self.vsource.addItem("")
        self.gridLayout.addWidget(self.vsource, 1, 1, 1, 1)
        self.file_name = QtWidgets.QLineEdit(self.frame)
        self.file_name.setObjectName("file_name")
        self.gridLayout.addWidget(self.file_name, 0, 1, 1, 1)
        self.source_label = QtWidgets.QLabel(self.frame)
        self.source_label.setObjectName("source_label")
        self.gridLayout.addWidget(self.source_label, 1, 0, 1, 1)
        self.fname_label = QtWidgets.QLabel(self.frame)
        self.fname_label.setObjectName("fname_label")
        self.gridLayout.addWidget(self.fname_label, 0, 0, 1, 1)
        self.average_label = QtWidgets.QLabel(self.frame)
        self.average_label.setObjectName("average_label")
        self.gridLayout.addWidget(self.average_label, 13, 0, 1, 1)
        self.setPwidth_label = QtWidgets.QLabel(self.frame)
        self.setPwidth_label.setObjectName("setPwidth_label")
        self.gridLayout.addWidget(self.setPwidth_label, 3, 0, 1, 1)
        self.resetPwidth_label = QtWidgets.QLabel(self.frame)
        self.resetPwidth_label.setObjectName("resetPwidth_label")
        self.gridLayout.addWidget(self.resetPwidth_label, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resetPwidth = QtWidgets.QDoubleSpinBox(self.frame)
        self.resetPwidth.setWrapping(False)
        self.resetPwidth.setDecimals(1)
        self.resetPwidth.setProperty("value", 1.0)
        self.resetPwidth.setObjectName("resetPwidth")
        self.horizontalLayout_2.addWidget(self.resetPwidth)
        self.resetTimeUnit = QtWidgets.QComboBox(self.frame)
        self.resetTimeUnit.setMaximumSize(QtCore.QSize(41, 22))
        self.resetTimeUnit.setObjectName("resetTimeUnit")
        self.resetTimeUnit.addItem("")
        self.resetTimeUnit.addItem("")
        self.resetTimeUnit.addItem("")
        self.horizontalLayout_2.addWidget(self.resetTimeUnit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 1, 1, 1)
        self.time_label = QtWidgets.QLabel(self.frame)
        self.time_label.setObjectName("time_label")
        self.gridLayout.addWidget(self.time_label, 11, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.setV = QtWidgets.QDoubleSpinBox(self.frame)
        self.setV.setMinimumSize(QtCore.QSize(115, 0))
        self.setV.setDecimals(3)
        self.setV.setMinimum(-5.0)
        self.setV.setMaximum(5.0)
        self.setV.setSingleStep(0.001)
        self.setV.setProperty("value", -3.0)
        self.setV.setObjectName("setV")
        self.horizontalLayout_4.addWidget(self.setV)
        self.setVcheck = QtWidgets.QCheckBox(self.frame)
        self.setVcheck.setText("")
        self.setVcheck.setChecked(True)
        self.setVcheck.setObjectName("setVcheck")
        self.horizontalLayout_4.addWidget(self.setVcheck)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.resetV = QtWidgets.QDoubleSpinBox(self.frame)
        self.resetV.setMinimumSize(QtCore.QSize(115, 0))
        self.resetV.setDecimals(3)
        self.resetV.setMinimum(-9.0)
        self.resetV.setMaximum(10.0)
        self.resetV.setSingleStep(0.001)
        self.resetV.setProperty("value", 3.0)
        self.resetV.setObjectName("resetV")
        self.horizontalLayout_5.addWidget(self.resetV)
        self.resetVcheck = QtWidgets.QCheckBox(self.frame)
        self.resetVcheck.setText("")
        self.resetVcheck.setChecked(True)
        self.resetVcheck.setObjectName("resetVcheck")
        self.horizontalLayout_5.addWidget(self.resetVcheck)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.time_hr = QtWidgets.QTimeEdit(self.frame)
        self.time_hr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_hr.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.time_hr.setMinimumTime(QtCore.QTime(0, 0, 1))
        self.time_hr.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.time_hr.setTime(QtCore.QTime(2, 46, 40))
        self.time_hr.setObjectName("time_hr")
        self.horizontalLayout_6.addWidget(self.time_hr)
        self.time_sec = QtWidgets.QSpinBox(self.frame)
        self.time_sec.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.time_sec.setMinimum(1)
        self.time_sec.setMaximum(86400)
        self.time_sec.setProperty("value", 10000)
        self.time_sec.setObjectName("time_sec")
        self.horizontalLayout_6.addWidget(self.time_sec)
        self.time = QtWidgets.QLabel(self.frame)
        self.time.setObjectName("time")
        self.horizontalLayout_6.addWidget(self.time)
        self.gridLayout.addLayout(self.horizontalLayout_6, 11, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.iLimit = QtWidgets.QDoubleSpinBox(self.frame)
        self.iLimit.setMinimumSize(QtCore.QSize(0, 0))
        self.iLimit.setDecimals(3)
        self.iLimit.setMinimum(-500.0)
        self.iLimit.setMaximum(500.0)
        self.iLimit.setSingleStep(0.1)
        self.iLimit.setProperty("value", 1.0)
        self.iLimit.setObjectName("iLimit")
        self.horizontalLayout_7.addWidget(self.iLimit)
        self.resistor = QtWidgets.QLabel(self.frame)
        self.resistor.setObjectName("resistor")
        self.horizontalLayout_7.addWidget(self.resistor)
        self.gridLayout.addLayout(self.horizontalLayout_7, 10, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.retentionPlot = PlotWidget(Retention)
        self.retentionPlot.setMinimumSize(QtCore.QSize(411, 379))
        self.retentionPlot.setObjectName("retentionPlot")
        self.gridLayout_2.addWidget(self.retentionPlot, 0, 1, 2, 1)
        self.widget = QtWidgets.QWidget(Retention)
        self.widget.setMinimumSize(QtCore.QSize(221, 209))
        self.widget.setMaximumSize(QtCore.QSize(293, 10000))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comment_checkBox = QtWidgets.QCheckBox(self.widget)
        self.comment_checkBox.setObjectName("comment_checkBox")
        self.verticalLayout.addWidget(self.comment_checkBox)
        self.commentBox = QtWidgets.QTextEdit(self.widget)
        self.commentBox.setEnabled(False)
        self.commentBox.setObjectName("commentBox")
        self.verticalLayout.addWidget(self.commentBox)
        self.timeTaken = QtWidgets.QLineEdit(self.widget)
        self.timeTaken.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.timeTaken.setPalette(palette)
        self.timeTaken.setText("")
        self.timeTaken.setAlignment(QtCore.Qt.AlignCenter)
        self.timeTaken.setReadOnly(True)
        self.timeTaken.setObjectName("timeTaken")
        self.verticalLayout.addWidget(self.timeTaken)
        self.start_Button = QtWidgets.QPushButton(self.widget)
        self.start_Button.setObjectName("start_Button")
        self.verticalLayout.addWidget(self.start_Button)
        self.skip_Button = QtWidgets.QPushButton(self.widget)
        self.skip_Button.setObjectName("skip_Button")
        self.verticalLayout.addWidget(self.skip_Button)
        self.abort_Button = QtWidgets.QPushButton(self.widget)
        self.abort_Button.setObjectName("abort_Button")
        self.verticalLayout.addWidget(self.abort_Button)
        self.status = QtWidgets.QLineEdit(self.widget)
        self.status.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.status.setPalette(palette)
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setReadOnly(True)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.gridLayout_2.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(Retention)
        self.setTimeUnit.setCurrentIndex(0)
        self.vsource.setCurrentIndex(0)
        self.resetTimeUnit.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Retention)
        Retention.setTabOrder(self.file_name, self.vsource)
        Retention.setTabOrder(self.vsource, self.setV)
        Retention.setTabOrder(self.setV, self.setVcheck)
        Retention.setTabOrder(self.setVcheck, self.setPwidth)
        Retention.setTabOrder(self.setPwidth, self.setTimeUnit)
        Retention.setTabOrder(self.setTimeUnit, self.resetV)
        Retention.setTabOrder(self.resetV, self.resetVcheck)
        Retention.setTabOrder(self.resetVcheck, self.resetPwidth)
        Retention.setTabOrder(self.resetPwidth, self.resetTimeUnit)
        Retention.setTabOrder(self.resetTimeUnit, self.iLimit)
        Retention.setTabOrder(self.iLimit, self.time_hr)
        Retention.setTabOrder(self.time_hr, self.time_sec)
        Retention.setTabOrder(self.time_sec, self.read_voltage)
        Retention.setTabOrder(self.read_voltage, self.avg)
        Retention.setTabOrder(self.avg, self.temp_check)
        Retention.setTabOrder(self.temp_check, self.temperature)
        Retention.setTabOrder(self.temperature, self.comment_checkBox)
        Retention.setTabOrder(self.comment_checkBox, self.commentBox)
        Retention.setTabOrder(self.commentBox, self.timeTaken)
        Retention.setTabOrder(self.timeTaken, self.start_Button)
        Retention.setTabOrder(self.start_Button, self.skip_Button)
        Retention.setTabOrder(self.skip_Button, self.abort_Button)
        Retention.setTabOrder(self.abort_Button, self.status)

    def retranslateUi(self, Retention):
        _translate = QtCore.QCoreApplication.translate
        Retention.setWindowTitle(_translate("Retention", "Retention"))
        self.Program_label.setText(_translate("Retention", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#0000ff;\">Retention Test</span></p></body></html>"))
        self.setting_label.setText(_translate("Retention", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#aa0000;\">Settings</span></p></body></html>"))
        self.setTimeUnit.setToolTip(_translate("Retention", "<html><head/><body><p>Select time unit</p></body></html>"))
        self.setTimeUnit.setItemText(0, _translate("Retention", "µs"))
        self.setTimeUnit.setItemText(1, _translate("Retention", "ms"))
        self.setTimeUnit.setItemText(2, _translate("Retention", "s"))
        self.points_label.setText(_translate("Retention", "Points"))
        self.readVoltage_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">Read Voltage (V)</span></p></body></html>"))
        self.temperature.setToolTip(_translate("Retention", "<html><head/><body><p>Temperature range will depend on the type of heater</p></body></html>"))
        self.Ilimit_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">Current Limit (mA)</span></p></body></html>"))
        self.temp_check.setToolTip(_translate("Retention", "<html><head/><body><p>Use temperature only if temperature controller is attached</p></body></html>"))
        self.temp_check.setText(_translate("Retention", "Temperature (K)"))
        self.resetV_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">Reset Voltage (V)</span></p></body></html>"))
        self.setV_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">Set Voltage (V)</span></p></body></html>"))
        self.vsource.setItemText(0, _translate("Retention", "Keyssight 2920B"))
        self.vsource.setItemText(1, _translate("Retention", "Keithley 2450"))
        self.vsource.setItemText(2, _translate("Retention", "Tektronix AFG1022"))
        self.file_name.setText(_translate("Retention", "Sample_Retention"))
        self.source_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">Pulse Source</span></p></body></html>"))
        self.fname_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">File Name</span></p></body></html>"))
        self.average_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">Average over</span></p></body></html>"))
        self.setPwidth_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">Set Pulse width</span></p></body></html>"))
        self.resetPwidth_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">Reset Pulse width</span></p></body></html>"))
        self.resetTimeUnit.setToolTip(_translate("Retention", "<html><head/><body><p>Select time unit</p></body></html>"))
        self.resetTimeUnit.setItemText(0, _translate("Retention", "µs"))
        self.resetTimeUnit.setItemText(1, _translate("Retention", "ms"))
        self.resetTimeUnit.setItemText(2, _translate("Retention", "s"))
        self.time_label.setText(_translate("Retention", "<html><head/><body><p><span style=\" font-size:10pt;\">Measurement Time</span></p></body></html>"))
        self.setV.setToolTip(_translate("Retention", "<html><head/><body><p>Max -10 V</p></body></html>"))
        self.resetV.setToolTip(_translate("Retention", "<html><head/><body><p>Max 10 V</p></body></html>"))
        self.time_hr.setToolTip(_translate("Retention", "<html><head/><body><p>hour:minute:second</p><p>Maximum 1 day</p></body></html>"))
        self.time_hr.setDisplayFormat(_translate("Retention", "h:mm:ss"))
        self.time_sec.setToolTip(_translate("Retention", "<html><head/><body><p>Total time in seconds</p><p>maximum: 86399</p></body></html>"))
        self.time.setText(_translate("Retention", "s"))
        self.iLimit.setToolTip(_translate("Retention", "<html><head/><body><p>Max 10 V</p></body></html>"))
        self.resistor.setText(_translate("Retention", "~ 1  kΩ"))
        self.comment_checkBox.setText(_translate("Retention", "Add Comments"))
        self.start_Button.setToolTip(_translate("Retention", "<html><head/><body><p>Click to start the experiment</p></body></html>"))
        self.start_Button.setText(_translate("Retention", "START"))
        self.skip_Button.setText(_translate("Retention", "Skip to Next"))
        self.abort_Button.setToolTip(_translate("Retention", "<html><head/><body><p>Click to abort the experiment</p></body></html>"))
        self.abort_Button.setText(_translate("Retention", "Abort"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Retention = QtWidgets.QWidget()
    ui = Ui_Retention()
    ui.setupUi(Retention)
    Retention.show()
    sys.exit(app.exec_())

