# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Switching_Speed.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Switch(object):
    def setupUi(self, Switch):
        Switch.setObjectName("Switch")
        Switch.resize(1050, 661)
        Switch.setMinimumSize(QtCore.QSize(1050, 661))
        self.gridLayout_2 = QtWidgets.QGridLayout(Switch)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(Switch)
        self.widget.setMinimumSize(QtCore.QSize(350, 449))
        self.widget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_label = QtWidgets.QLabel(self.widget)
        self.title_label.setMinimumSize(QtCore.QSize(0, 24))
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.title_label.setObjectName("title_label")
        self.verticalLayout_2.addWidget(self.title_label)
        self.setting_label = QtWidgets.QLabel(self.widget)
        self.setting_label.setMinimumSize(QtCore.QSize(0, 24))
        self.setting_label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.setting_label.setObjectName("setting_label")
        self.verticalLayout_2.addWidget(self.setting_label)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.set_pulseWidthRange_label = QtWidgets.QLabel(self.frame)
        self.set_pulseWidthRange_label.setObjectName("set_pulseWidthRange_label")
        self.gridLayout.addWidget(self.set_pulseWidthRange_label, 4, 1, 1, 1)
        self.resetV_label = QtWidgets.QLabel(self.frame)
        self.resetV_label.setObjectName("resetV_label")
        self.gridLayout.addWidget(self.resetV_label, 6, 1, 1, 1)
        self.read_voltage = QtWidgets.QDoubleSpinBox(self.frame)
        self.read_voltage.setDecimals(3)
        self.read_voltage.setMaximum(10.0)
        self.read_voltage.setSingleStep(0.1)
        self.read_voltage.setProperty("value", 0.1)
        self.read_voltage.setObjectName("read_voltage")
        self.gridLayout.addWidget(self.read_voltage, 11, 2, 1, 1)
        self.temperature = QtWidgets.QDoubleSpinBox(self.frame)
        self.temperature.setEnabled(False)
        self.temperature.setMaximum(600.0)
        self.temperature.setProperty("value", 300.0)
        self.temperature.setObjectName("temperature")
        self.gridLayout.addWidget(self.temperature, 16, 2, 1, 1)
        self.source = QtWidgets.QComboBox(self.frame)
        self.source.setEnabled(True)
        self.source.setObjectName("source")
        self.source.addItem("")
        self.source.addItem("")
        self.gridLayout.addWidget(self.source, 2, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.avg = QtWidgets.QSpinBox(self.frame)
        self.avg.setMaximumSize(QtCore.QSize(50, 20))
        self.avg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avg.setMinimum(1)
        self.avg.setMaximum(1000)
        self.avg.setProperty("value", 5)
        self.avg.setObjectName("avg")
        self.horizontalLayout_4.addWidget(self.avg)
        self.avgread_label = QtWidgets.QLabel(self.frame)
        self.avgread_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.avgread_label.setObjectName("avgread_label")
        self.horizontalLayout_4.addWidget(self.avgread_label)
        self.gridLayout.addLayout(self.horizontalLayout_4, 12, 2, 1, 1)
        self.file_name = QtWidgets.QLineEdit(self.frame)
        self.file_name.setObjectName("file_name")
        self.gridLayout.addWidget(self.file_name, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setV = QtWidgets.QDoubleSpinBox(self.frame)
        self.setV.setDecimals(3)
        self.setV.setMinimum(-50.0)
        self.setV.setMaximum(49.0)
        self.setV.setSingleStep(0.1)
        self.setV.setProperty("value", -3.0)
        self.setV.setObjectName("setV")
        self.horizontalLayout_2.addWidget(self.setV)
        self.setV_check = QtWidgets.QCheckBox(self.frame)
        self.setV_check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.setV_check.setText("")
        self.setV_check.setChecked(True)
        self.setV_check.setObjectName("setV_check")
        self.horizontalLayout_2.addWidget(self.setV_check)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resetV = QtWidgets.QDoubleSpinBox(self.frame)
        self.resetV.setDecimals(3)
        self.resetV.setMinimum(-49.0)
        self.resetV.setMaximum(50.0)
        self.resetV.setSingleStep(0.001)
        self.resetV.setProperty("value", 3.0)
        self.resetV.setObjectName("resetV")
        self.horizontalLayout_3.addWidget(self.resetV)
        self.resetV_check = QtWidgets.QCheckBox(self.frame)
        self.resetV_check.setMaximumSize(QtCore.QSize(20, 16777215))
        self.resetV_check.setText("")
        self.resetV_check.setChecked(True)
        self.resetV_check.setObjectName("resetV_check")
        self.horizontalLayout_3.addWidget(self.resetV_check)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 2, 1, 1)
        self.reset_pulseWidthRange_label = QtWidgets.QLabel(self.frame)
        self.reset_pulseWidthRange_label.setObjectName("reset_pulseWidthRange_label")
        self.gridLayout.addWidget(self.reset_pulseWidthRange_label, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.temp_check = QtWidgets.QCheckBox(self.frame)
        self.temp_check.setObjectName("temp_check")
        self.gridLayout.addWidget(self.temp_check, 16, 1, 1, 1)
        self.avg_label = QtWidgets.QLabel(self.frame)
        self.avg_label.setObjectName("avg_label")
        self.gridLayout.addWidget(self.avg_label, 12, 1, 1, 1)
        self.setV_label = QtWidgets.QLabel(self.frame)
        self.setV_label.setObjectName("setV_label")
        self.gridLayout.addWidget(self.setV_label, 3, 1, 1, 1)
        self.readV_label = QtWidgets.QLabel(self.frame)
        self.readV_label.setObjectName("readV_label")
        self.gridLayout.addWidget(self.readV_label, 11, 1, 1, 1)
        self.fname_label = QtWidgets.QLabel(self.frame)
        self.fname_label.setObjectName("fname_label")
        self.gridLayout.addWidget(self.fname_label, 1, 1, 1, 1)
        self.Ilimit_label = QtWidgets.QLabel(self.frame)
        self.Ilimit_label.setObjectName("Ilimit_label")
        self.gridLayout.addWidget(self.Ilimit_label, 9, 1, 1, 1)
        self.Ilimit = QtWidgets.QDoubleSpinBox(self.frame)
        self.Ilimit.setDecimals(3)
        self.Ilimit.setMaximum(500.0)
        self.Ilimit.setSingleStep(0.001)
        self.Ilimit.setProperty("value", 1.0)
        self.Ilimit.setObjectName("Ilimit")
        self.gridLayout.addWidget(self.Ilimit, 9, 2, 1, 1)
        self.fixedSet_pulseWidth_label = QtWidgets.QLabel(self.frame)
        self.fixedSet_pulseWidth_label.setObjectName("fixedSet_pulseWidth_label")
        self.gridLayout.addWidget(self.fixedSet_pulseWidth_label, 8, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fixedReset_pulseWidth = QtWidgets.QDoubleSpinBox(self.frame)
        self.fixedReset_pulseWidth.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.fixedReset_pulseWidth.setDecimals(2)
        self.fixedReset_pulseWidth.setMaximum(1000.0)
        self.fixedReset_pulseWidth.setProperty("value", 1.0)
        self.fixedReset_pulseWidth.setObjectName("fixedReset_pulseWidth")
        self.horizontalLayout.addWidget(self.fixedReset_pulseWidth)
        self.fixedReset_timeUnit = QtWidgets.QComboBox(self.frame)
        self.fixedReset_timeUnit.setMaximumSize(QtCore.QSize(41, 22))
        self.fixedReset_timeUnit.setObjectName("fixedReset_timeUnit")
        self.fixedReset_timeUnit.addItem("")
        self.fixedReset_timeUnit.addItem("")
        self.fixedReset_timeUnit.addItem("")
        self.horizontalLayout.addWidget(self.fixedReset_timeUnit)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 2, 1, 1)
        self.fixedReset_pulseWidth_label = QtWidgets.QLabel(self.frame)
        self.fixedReset_pulseWidth_label.setObjectName("fixedReset_pulseWidth_label")
        self.gridLayout.addWidget(self.fixedReset_pulseWidth_label, 5, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.set_pulseWidthStart = QtWidgets.QDoubleSpinBox(self.frame)
        self.set_pulseWidthStart.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_pulseWidthStart.setDecimals(2)
        self.set_pulseWidthStart.setMaximum(1000.0)
        self.set_pulseWidthStart.setProperty("value", 0.01)
        self.set_pulseWidthStart.setObjectName("set_pulseWidthStart")
        self.horizontalLayout_5.addWidget(self.set_pulseWidthStart)
        self.set_timeUnit_1 = QtWidgets.QComboBox(self.frame)
        self.set_timeUnit_1.setMaximumSize(QtCore.QSize(41, 22))
        self.set_timeUnit_1.setObjectName("set_timeUnit_1")
        self.set_timeUnit_1.addItem("")
        self.set_timeUnit_1.addItem("")
        self.set_timeUnit_1.addItem("")
        self.horizontalLayout_5.addWidget(self.set_timeUnit_1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.set_pulseWidthEnd = QtWidgets.QDoubleSpinBox(self.frame)
        self.set_pulseWidthEnd.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.set_pulseWidthEnd.setDecimals(1)
        self.set_pulseWidthEnd.setMaximum(1000.0)
        self.set_pulseWidthEnd.setProperty("value", 100.0)
        self.set_pulseWidthEnd.setObjectName("set_pulseWidthEnd")
        self.horizontalLayout_5.addWidget(self.set_pulseWidthEnd)
        self.set_timeUnit_2 = QtWidgets.QComboBox(self.frame)
        self.set_timeUnit_2.setMaximumSize(QtCore.QSize(41, 22))
        self.set_timeUnit_2.setObjectName("set_timeUnit_2")
        self.set_timeUnit_2.addItem("")
        self.set_timeUnit_2.addItem("")
        self.set_timeUnit_2.addItem("")
        self.horizontalLayout_5.addWidget(self.set_timeUnit_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.reset_pulseWidthStart = QtWidgets.QDoubleSpinBox(self.frame)
        self.reset_pulseWidthStart.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.reset_pulseWidthStart.setDecimals(2)
        self.reset_pulseWidthStart.setMaximum(1000.0)
        self.reset_pulseWidthStart.setProperty("value", 0.01)
        self.reset_pulseWidthStart.setObjectName("reset_pulseWidthStart")
        self.horizontalLayout_6.addWidget(self.reset_pulseWidthStart)
        self.reset_timeUnit_1 = QtWidgets.QComboBox(self.frame)
        self.reset_timeUnit_1.setMaximumSize(QtCore.QSize(41, 22))
        self.reset_timeUnit_1.setObjectName("reset_timeUnit_1")
        self.reset_timeUnit_1.addItem("")
        self.reset_timeUnit_1.addItem("")
        self.reset_timeUnit_1.addItem("")
        self.horizontalLayout_6.addWidget(self.reset_timeUnit_1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.reset_pulseWidthEnd = QtWidgets.QDoubleSpinBox(self.frame)
        self.reset_pulseWidthEnd.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.reset_pulseWidthEnd.setDecimals(1)
        self.reset_pulseWidthEnd.setMaximum(1000.0)
        self.reset_pulseWidthEnd.setProperty("value", 100.0)
        self.reset_pulseWidthEnd.setObjectName("reset_pulseWidthEnd")
        self.horizontalLayout_6.addWidget(self.reset_pulseWidthEnd)
        self.reset_timeUnit_2 = QtWidgets.QComboBox(self.frame)
        self.reset_timeUnit_2.setMaximumSize(QtCore.QSize(41, 22))
        self.reset_timeUnit_2.setObjectName("reset_timeUnit_2")
        self.reset_timeUnit_2.addItem("")
        self.reset_timeUnit_2.addItem("")
        self.reset_timeUnit_2.addItem("")
        self.horizontalLayout_6.addWidget(self.reset_timeUnit_2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 7, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fixedSet_pulseWidth = QtWidgets.QDoubleSpinBox(self.frame)
        self.fixedSet_pulseWidth.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.fixedSet_pulseWidth.setDecimals(2)
        self.fixedSet_pulseWidth.setMaximum(1000.0)
        self.fixedSet_pulseWidth.setProperty("value", 1.0)
        self.fixedSet_pulseWidth.setObjectName("fixedSet_pulseWidth")
        self.horizontalLayout_7.addWidget(self.fixedSet_pulseWidth)
        self.fixedSet_timeUnit = QtWidgets.QComboBox(self.frame)
        self.fixedSet_timeUnit.setMaximumSize(QtCore.QSize(41, 22))
        self.fixedSet_timeUnit.setObjectName("fixedSet_timeUnit")
        self.fixedSet_timeUnit.addItem("")
        self.fixedSet_timeUnit.addItem("")
        self.fixedSet_timeUnit.addItem("")
        self.horizontalLayout_7.addWidget(self.fixedSet_timeUnit)
        self.gridLayout.addLayout(self.horizontalLayout_7, 8, 2, 1, 1)
        self.npoints_label = QtWidgets.QLabel(self.frame)
        self.npoints_label.setMinimumSize(QtCore.QSize(0, 25))
        self.npoints_label.setObjectName("npoints_label")
        self.gridLayout.addWidget(self.npoints_label, 10, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.nPulses = QtWidgets.QSpinBox(self.frame)
        self.nPulses.setMinimumSize(QtCore.QSize(0, 25))
        self.nPulses.setMinimum(5)
        self.nPulses.setMaximum(100)
        self.nPulses.setProperty("value", 50)
        self.nPulses.setObjectName("nPulses")
        self.horizontalLayout_8.addWidget(self.nPulses)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_8, 10, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(Switch)
        self.widget1.setMinimumSize(QtCore.QSize(350, 151))
        self.widget1.setMaximumSize(QtCore.QSize(350, 10000))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comment_checkBox = QtWidgets.QCheckBox(self.widget1)
        self.comment_checkBox.setObjectName("comment_checkBox")
        self.verticalLayout.addWidget(self.comment_checkBox)
        self.commentBox = QtWidgets.QTextEdit(self.widget1)
        self.commentBox.setEnabled(False)
        self.commentBox.setObjectName("commentBox")
        self.verticalLayout.addWidget(self.commentBox)
        self.applyPulse_Button = QtWidgets.QPushButton(self.widget1)
        self.applyPulse_Button.setObjectName("applyPulse_Button")
        self.verticalLayout.addWidget(self.applyPulse_Button)
        self.clearGraph_Button = QtWidgets.QPushButton(self.widget1)
        self.clearGraph_Button.setObjectName("clearGraph_Button")
        self.verticalLayout.addWidget(self.clearGraph_Button)
        self.save_Button = QtWidgets.QPushButton(self.widget1)
        self.save_Button.setObjectName("save_Button")
        self.verticalLayout.addWidget(self.save_Button)
        self.statusbar = QtWidgets.QLineEdit(self.widget1)
        self.statusbar.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.statusbar.setPalette(palette)
        self.statusbar.setText("")
        self.statusbar.setAlignment(QtCore.Qt.AlignCenter)
        self.statusbar.setReadOnly(True)
        self.statusbar.setObjectName("statusbar")
        self.verticalLayout.addWidget(self.statusbar)
        self.gridLayout_2.addWidget(self.widget1, 1, 0, 1, 1)
        self.graphWidget = PlotWidget(Switch)
        self.graphWidget.setMinimumSize(QtCore.QSize(411, 379))
        self.graphWidget.setObjectName("graphWidget")
        self.gridLayout_2.addWidget(self.graphWidget, 0, 1, 2, 1)

        self.retranslateUi(Switch)
        self.source.setCurrentIndex(0)
        self.fixedReset_timeUnit.setCurrentIndex(1)
        self.set_timeUnit_1.setCurrentIndex(0)
        self.set_timeUnit_2.setCurrentIndex(1)
        self.reset_timeUnit_1.setCurrentIndex(0)
        self.reset_timeUnit_2.setCurrentIndex(1)
        self.fixedSet_timeUnit.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Switch)
        Switch.setTabOrder(self.file_name, self.source)
        Switch.setTabOrder(self.source, self.setV)
        Switch.setTabOrder(self.setV, self.setV_check)
        Switch.setTabOrder(self.setV_check, self.set_pulseWidthStart)
        Switch.setTabOrder(self.set_pulseWidthStart, self.set_timeUnit_1)
        Switch.setTabOrder(self.set_timeUnit_1, self.set_pulseWidthEnd)
        Switch.setTabOrder(self.set_pulseWidthEnd, self.set_timeUnit_2)
        Switch.setTabOrder(self.set_timeUnit_2, self.fixedReset_pulseWidth)
        Switch.setTabOrder(self.fixedReset_pulseWidth, self.fixedReset_timeUnit)
        Switch.setTabOrder(self.fixedReset_timeUnit, self.resetV)
        Switch.setTabOrder(self.resetV, self.resetV_check)
        Switch.setTabOrder(self.resetV_check, self.reset_pulseWidthStart)
        Switch.setTabOrder(self.reset_pulseWidthStart, self.reset_timeUnit_1)
        Switch.setTabOrder(self.reset_timeUnit_1, self.reset_pulseWidthEnd)
        Switch.setTabOrder(self.reset_pulseWidthEnd, self.reset_timeUnit_2)
        Switch.setTabOrder(self.reset_timeUnit_2, self.fixedSet_pulseWidth)
        Switch.setTabOrder(self.fixedSet_pulseWidth, self.fixedSet_timeUnit)
        Switch.setTabOrder(self.fixedSet_timeUnit, self.Ilimit)
        Switch.setTabOrder(self.Ilimit, self.nPulses)
        Switch.setTabOrder(self.nPulses, self.comboBox)
        Switch.setTabOrder(self.comboBox, self.read_voltage)
        Switch.setTabOrder(self.read_voltage, self.avg)
        Switch.setTabOrder(self.avg, self.temp_check)
        Switch.setTabOrder(self.temp_check, self.temperature)
        Switch.setTabOrder(self.temperature, self.comment_checkBox)
        Switch.setTabOrder(self.comment_checkBox, self.commentBox)
        Switch.setTabOrder(self.commentBox, self.applyPulse_Button)
        Switch.setTabOrder(self.applyPulse_Button, self.clearGraph_Button)
        Switch.setTabOrder(self.clearGraph_Button, self.save_Button)
        Switch.setTabOrder(self.save_Button, self.statusbar)

    def retranslateUi(self, Switch):
        _translate = QtCore.QCoreApplication.translate
        Switch.setWindowTitle(_translate("Switch", "Switching Speed"))
        self.title_label.setText(_translate("Switch", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#0000ff;\">Switching Speed Test</span></p></body></html>"))
        self.setting_label.setText(_translate("Switch", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#aa0000;\">Settings</span></p></body></html>"))
        self.set_pulseWidthRange_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Set Pulse Width range</span></p></body></html>"))
        self.resetV_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Reset Voltage (V)</span></p></body></html>"))
        self.temperature.setToolTip(_translate("Switch", "<html><head/><body><p>Temperature range will depend on the type of heater</p></body></html>"))
        self.source.setItemText(0, _translate("Switch", "Keysight B2902B"))
        self.source.setItemText(1, _translate("Switch", "Tektronix AFG1022"))
        self.avgread_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Readings</span></p></body></html>"))
        self.file_name.setText(_translate("Switch", "Sample_SwitchSpeed"))
        self.setV.setToolTip(_translate("Switch", "<html><head/><body><p>Max -10 V</p></body></html>"))
        self.resetV.setToolTip(_translate("Switch", "<html><head/><body><p>Max 10 V</p></body></html>"))
        self.reset_pulseWidthRange_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Reset Pulse width range</span></p></body></html>"))
        self.label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Voltage Source</span></p></body></html>"))
        self.temp_check.setToolTip(_translate("Switch", "<html><head/><body><p>Use temperature only if temperature controller is attached</p></body></html>"))
        self.temp_check.setText(_translate("Switch", "Temperature (K)"))
        self.avg_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Average over</span></p></body></html>"))
        self.setV_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Set Voltage (V)</span></p></body></html>"))
        self.readV_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Read Voltage (V)</span></p></body></html>"))
        self.fname_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">File Name</span></p></body></html>"))
        self.Ilimit_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Current Limit (mA)</span></p></body></html>"))
        self.Ilimit.setToolTip(_translate("Switch", "<html><head/><body><p>The compliance current, which protects the sample from full breakdown</p></body></html>"))
        self.fixedSet_pulseWidth_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Fixed set pulse width</span></p></body></html>"))
        self.fixedReset_timeUnit.setToolTip(_translate("Switch", "<html><head/><body><p>Select time unit. Time below 50 ms may not be reliable for Keithley 2450</p></body></html>"))
        self.fixedReset_timeUnit.setItemText(0, _translate("Switch", "µs"))
        self.fixedReset_timeUnit.setItemText(1, _translate("Switch", "ms"))
        self.fixedReset_timeUnit.setItemText(2, _translate("Switch", "s"))
        self.fixedReset_pulseWidth_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Fixed reset pulse width</span></p></body></html>"))
        self.set_timeUnit_1.setToolTip(_translate("Switch", "<html><head/><body><p>Select time unit. Time below 50 ms may not be reliable for Keithley 2450</p></body></html>"))
        self.set_timeUnit_1.setItemText(0, _translate("Switch", "µs"))
        self.set_timeUnit_1.setItemText(1, _translate("Switch", "ms"))
        self.set_timeUnit_1.setItemText(2, _translate("Switch", "s"))
        self.label_3.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">to</span></p></body></html>"))
        self.set_timeUnit_2.setToolTip(_translate("Switch", "<html><head/><body><p>Select time unit. Time below 50 ms may not be reliable for Keithley 2450</p></body></html>"))
        self.set_timeUnit_2.setItemText(0, _translate("Switch", "µs"))
        self.set_timeUnit_2.setItemText(1, _translate("Switch", "ms"))
        self.set_timeUnit_2.setItemText(2, _translate("Switch", "s"))
        self.reset_timeUnit_1.setToolTip(_translate("Switch", "<html><head/><body><p>Select time unit. Time below 50 ms may not be reliable for Keithley 2450</p></body></html>"))
        self.reset_timeUnit_1.setItemText(0, _translate("Switch", "µs"))
        self.reset_timeUnit_1.setItemText(1, _translate("Switch", "ms"))
        self.reset_timeUnit_1.setItemText(2, _translate("Switch", "s"))
        self.label_4.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">to</span></p></body></html>"))
        self.reset_timeUnit_2.setToolTip(_translate("Switch", "<html><head/><body><p>Select time unit. Time below 50 ms may not be reliable for Keithley 2450</p></body></html>"))
        self.reset_timeUnit_2.setItemText(0, _translate("Switch", "µs"))
        self.reset_timeUnit_2.setItemText(1, _translate("Switch", "ms"))
        self.reset_timeUnit_2.setItemText(2, _translate("Switch", "s"))
        self.fixedSet_timeUnit.setToolTip(_translate("Switch", "<html><head/><body><p>Select time unit. Time below 50 ms may not be reliable for Keithley 2450</p></body></html>"))
        self.fixedSet_timeUnit.setItemText(0, _translate("Switch", "µs"))
        self.fixedSet_timeUnit.setItemText(1, _translate("Switch", "ms"))
        self.fixedSet_timeUnit.setItemText(2, _translate("Switch", "s"))
        self.npoints_label.setText(_translate("Switch", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of points</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Switch", "Log Scale"))
        self.comboBox.setItemText(1, _translate("Switch", "Linear Scale"))
        self.comment_checkBox.setText(_translate("Switch", "Add Comments"))
        self.applyPulse_Button.setToolTip(_translate("Switch", "<html><head/><body><p>Click to start the experiment</p></body></html>"))
        self.applyPulse_Button.setText(_translate("Switch", "Apply Pulse"))
        self.clearGraph_Button.setToolTip(_translate("Switch", "<html><head/><body><p>Click to abort the experiment</p></body></html>"))
        self.clearGraph_Button.setText(_translate("Switch", "Clear graph and start new measurement"))
        self.save_Button.setText(_translate("Switch", "Save Data"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Switch = QtWidgets.QWidget()
    ui = Ui_Switch()
    ui.setupUi(Switch)
    Switch.show()
    sys.exit(app.exec_())

